#+TITLE: Pi Day Project
#+SUBTITLE: Symbolic and Numerical Approximations for \pi
#+DATE: March 14 2022
#+LATEX_HEADER: \renewcommand\square[2]{#1#2^2}
#+LATEX_HEADER: \usepackage{cool}
#+LATEX_HEADER: \usepackage[small]{titlesec}
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
* Introduction
A simple celebration of Pi Day 2022 that utilises some things I find interesting about Lisp like HOFs and its ability to generate symbolic expressions (valid Lisp code) rather than just values.

The code generates symbolic (Lisp) expressions which represent particular infinite expressions for the value of $\pi$, computed to an arbitrary depth. It then uses a library to convert that to a valid LaTeX form, as well as evaluating the expression to get a numeric approximation for $\pi$.

Since this is written as a literate document, it's interspersed with some light rambling about the mathematics behind these approximations, which somebody hopefully finds interesting.

* Preamble
Our first task is to create a generalisation for expressing infinite series as symbolic expressions, given a method of generating the $i^{th}$ term of the series.
#+begin_src emacs-lisp :tangle yes :results silent
(require 'litex-mode)
(cl-defmacro series (expr &optional (var i) (lower 0) (upper n) (op ''+)) "Given a symbolic expression in terms of a variable like n or i, return a func which returns the long form as a symbolic expression"
             `(lambda (lnum unum)
                (cons ,op (-map (lambda (,var) ,expr) (number-sequence lnum unum)))
                )
             )
#+end_src

After that, we define some utilities and define our constant =LIM= which decides how far we should generate most series.
#+begin_src emacs-lisp :tangle yes :results silent
(defun odds (n)
  (-take n (-filter (lambda (x) (not (math-evenp x))) (number-sequence 0 (* 2 n))))
  )
(defun square (n)
  (expt n 2))
(defun sqrt (n)
  (expt n 0.5))

(cl-defun fib (n &optional (a 0) (b 1))
  (if (<= n 1)
      b
    (fib (- n 1) b (+ a b)))
  )
(setq LIM 50)
#+end_src
* Approximations
** Riemann Sum
It turns out that the sum $\Sum{\frac{1}{i^2}}{i,1,\infty}$ converges to $\frac{\pi^2}{6}$.

$sin(x)=0$ when $x=n\pi$ (including $x=0$), so we can approximate $sin$ as a product of $1-\frac{x}{n\pi}$, so $sin(x) \approx \ldots \times (1+ \frac{x}{n\pi}) \times x \times (1-\frac{x}{n\pi})$.
Since $(1-a)(1+a)=(1-a^2)$ this becomes $sin(x)= x\Prod{1-\frac{x^2}{n^2\pi^2}}{n,1, \infty}$.

The coefficient of $x^3$ in the Taylor series for $sin$ is $-\frac{1}{6}$.

Multiplying out the infinite product for $sin$ gets us $\frac{1}{6}=\frac{1}{\pi^2} \Sum{\frac{1}{n^2}}{n,1,\infty}$.

#+begin_src emacs-lisp :tangle yes :results value list :exports both
(let* (
       (riemann (series `(/ ,(float 1) (square ,i)) i 1 n))
       (wrapped `(* (sqrt 6) (sqrt ,(funcall riemann 1 LIM))))
       (tex (s-wrap (litex-lisp2latex-all wrapped ) "$" "$"))
       (evalled (eval wrapped))
       )
  (list tex evalled))
#+end_src

#+RESULTS:
- $\left( \sqrt{6} \right)\left( \sqrt{\left( \frac{1.0}{\left( \left( \square 1 \right) \right)} + \frac{1.0}{\left( \left( \square 2 \right) \right)} + \frac{1.0}{\left( \left( \square 3 \right) \right)} + \frac{1.0}{\left( \left( \square 4 \right) \right)} + \frac{1.0}{\left( \left( \square 5 \right) \right)} + \frac{1.0}{\left( \left( \square 6 \right) \right)} + \frac{1.0}{\left( \left( \square 7 \right) \right)} + \frac{1.0}{\left( \left( \square 8 \right) \right)} + \frac{1.0}{\left( \left( \square 9 \right) \right)} + \frac{1.0}{\left( \left( \square 10 \right) \right)} + \frac{1.0}{\left( \left( \square 11 \right) \right)} + \frac{1.0}{\left( \left( \square 12 \right) \right)} + \frac{1.0}{\left( \left( \square 13 \right) \right)} + \frac{1.0}{\left( \left( \square 14 \right) \right)} + \frac{1.0}{\left( \left( \square 15 \right) \right)} + \frac{1.0}{\left( \left( \square 16 \right) \right)} + \frac{1.0}{\left( \left( \square 17 \right) \right)} + \frac{1.0}{\left( \left( \square 18 \right) \right)} + \frac{1.0}{\left( \left( \square 19 \right) \right)} + \frac{1.0}{\left( \left( \square 20 \right) \right)} + \frac{1.0}{\left( \left( \square 21 \right) \right)} + \frac{1.0}{\left( \left( \square 22 \right) \right)} + \frac{1.0}{\left( \left( \square 23 \right) \right)} + \frac{1.0}{\left( \left( \square 24 \right) \right)} + \frac{1.0}{\left( \left( \square 25 \right) \right)} + \frac{1.0}{\left( \left( \square 26 \right) \right)} + \frac{1.0}{\left( \left( \square 27 \right) \right)} + \frac{1.0}{\left( \left( \square 28 \right) \right)} + \frac{1.0}{\left( \left( \square 29 \right) \right)} + \frac{1.0}{\left( \left( \square 30 \right) \right)} + \frac{1.0}{\left( \left( \square 31 \right) \right)} + \frac{1.0}{\left( \left( \square 32 \right) \right)} + \frac{1.0}{\left( \left( \square 33 \right) \right)} + \frac{1.0}{\left( \left( \square 34 \right) \right)} + \frac{1.0}{\left( \left( \square 35 \right) \right)} + \frac{1.0}{\left( \left( \square 36 \right) \right)} + \frac{1.0}{\left( \left( \square 37 \right) \right)} + \frac{1.0}{\left( \left( \square 38 \right) \right)} + \frac{1.0}{\left( \left( \square 39 \right) \right)} + \frac{1.0}{\left( \left( \square 40 \right) \right)} + \frac{1.0}{\left( \left( \square 41 \right) \right)} + \frac{1.0}{\left( \left( \square 42 \right) \right)} + \frac{1.0}{\left( \left( \square 43 \right) \right)} + \frac{1.0}{\left( \left( \square 44 \right) \right)} + \frac{1.0}{\left( \left( \square 45 \right) \right)} + \frac{1.0}{\left( \left( \square 46 \right) \right)} + \frac{1.0}{\left( \left( \square 47 \right) \right)} + \frac{1.0}{\left( \left( \square 48 \right) \right)} + \frac{1.0}{\left( \left( \square 49 \right) \right)} + \frac{1.0}{\left( \left( \square 50 \right) \right)} \right)} \right)$
- 3.122626522933726

** Wallis Integral
The Wallis product formula is one of the oldest expressions for $\pi$, and it hinges on the expansion of an integral $\Int{(1-x^2)^\frac{1}{2}}{x, 0, 1}$, which describes one fourth the area of the unit circle, i.e. $\frac{\pi}{4}$.

We can substitute $x=\cos(\theta)$, so this becomes $I_n=\Int{sin^n(\theta)}{\theta,0,\pi}$. Integrating this by parts gives us a recurrence relation, i.e a ratio between $I_n$ and $I_{n+2}$. Expanding this recurrence relation gives us the product $\pi=2\Prod{\frac{2k}{2k-1}\frac{2k}{2k+1}}{k,1,\infty}$.

#+begin_src emacs-lisp :tangle yes :results value list :exports both
(let* (
       (wallis (series `(* (/ ,(* 2.0 i) ,(- (* 2.0 i) 1)) (/ ,(* 2.0 i) ,(+ (* 2.0 i) 1))) i 1 n '*) )
       (wrapped `(* 2 ,(funcall wallis 1 LIM)))
       (tex (s-wrap (litex-lisp2latex-all wrapped) "$" "$"))
       (evalled (eval wrapped))
       )
  (list tex evalled)
  )
#+end_src

#+RESULTS:
- $2\frac{2.0}{\left( 1.0 \right)}\frac{2.0}{\left( 3.0 \right)}\frac{4.0}{\left( 3.0 \right)}\frac{4.0}{\left( 5.0 \right)}\frac{6.0}{\left( 5.0 \right)}\frac{6.0}{\left( 7.0 \right)}\frac{8.0}{\left( 7.0 \right)}\frac{8.0}{\left( 9.0 \right)}\frac{10.0}{\left( 9.0 \right)}\frac{10.0}{\left( 11.0 \right)}\frac{12.0}{\left( 11.0 \right)}\frac{12.0}{\left( 13.0 \right)}\frac{14.0}{\left( 13.0 \right)}\frac{14.0}{\left( 15.0 \right)}\frac{16.0}{\left( 15.0 \right)}\frac{16.0}{\left( 17.0 \right)}\frac{18.0}{\left( 17.0 \right)}\frac{18.0}{\left( 19.0 \right)}\frac{20.0}{\left( 19.0 \right)}\frac{20.0}{\left( 21.0 \right)}\frac{22.0}{\left( 21.0 \right)}\frac{22.0}{\left( 23.0 \right)}\frac{24.0}{\left( 23.0 \right)}\frac{24.0}{\left( 25.0 \right)}\frac{26.0}{\left( 25.0 \right)}\frac{26.0}{\left( 27.0 \right)}\frac{28.0}{\left( 27.0 \right)}\frac{28.0}{\left( 29.0 \right)}\frac{30.0}{\left( 29.0 \right)}\frac{30.0}{\left( 31.0 \right)}\frac{32.0}{\left( 31.0 \right)}\frac{32.0}{\left( 33.0 \right)}\frac{34.0}{\left( 33.0 \right)}\frac{34.0}{\left( 35.0 \right)}\frac{36.0}{\left( 35.0 \right)}\frac{36.0}{\left( 37.0 \right)}\frac{38.0}{\left( 37.0 \right)}\frac{38.0}{\left( 39.0 \right)}\frac{40.0}{\left( 39.0 \right)}\frac{40.0}{\left( 41.0 \right)}\frac{42.0}{\left( 41.0 \right)}\frac{42.0}{\left( 43.0 \right)}\frac{44.0}{\left( 43.0 \right)}\frac{44.0}{\left( 45.0 \right)}\frac{46.0}{\left( 45.0 \right)}\frac{46.0}{\left( 47.0 \right)}\frac{48.0}{\left( 47.0 \right)}\frac{48.0}{\left( 49.0 \right)}\frac{50.0}{\left( 49.0 \right)}\frac{50.0}{\left( 51.0 \right)}\frac{52.0}{\left( 51.0 \right)}\frac{52.0}{\left( 53.0 \right)}\frac{54.0}{\left( 53.0 \right)}\frac{54.0}{\left( 55.0 \right)}\frac{56.0}{\left( 55.0 \right)}\frac{56.0}{\left( 57.0 \right)}\frac{58.0}{\left( 57.0 \right)}\frac{58.0}{\left( 59.0 \right)}\frac{60.0}{\left( 59.0 \right)}\frac{60.0}{\left( 61.0 \right)}\frac{62.0}{\left( 61.0 \right)}\frac{62.0}{\left( 63.0 \right)}\frac{64.0}{\left( 63.0 \right)}\frac{64.0}{\left( 65.0 \right)}\frac{66.0}{\left( 65.0 \right)}\frac{66.0}{\left( 67.0 \right)}\frac{68.0}{\left( 67.0 \right)}\frac{68.0}{\left( 69.0 \right)}\frac{70.0}{\left( 69.0 \right)}\frac{70.0}{\left( 71.0 \right)}\frac{72.0}{\left( 71.0 \right)}\frac{72.0}{\left( 73.0 \right)}\frac{74.0}{\left( 73.0 \right)}\frac{74.0}{\left( 75.0 \right)}\frac{76.0}{\left( 75.0 \right)}\frac{76.0}{\left( 77.0 \right)}\frac{78.0}{\left( 77.0 \right)}\frac{78.0}{\left( 79.0 \right)}\frac{80.0}{\left( 79.0 \right)}\frac{80.0}{\left( 81.0 \right)}\frac{82.0}{\left( 81.0 \right)}\frac{82.0}{\left( 83.0 \right)}\frac{84.0}{\left( 83.0 \right)}\frac{84.0}{\left( 85.0 \right)}\frac{86.0}{\left( 85.0 \right)}\frac{86.0}{\left( 87.0 \right)}\frac{88.0}{\left( 87.0 \right)}\frac{88.0}{\left( 89.0 \right)}\frac{90.0}{\left( 89.0 \right)}\frac{90.0}{\left( 91.0 \right)}\frac{92.0}{\left( 91.0 \right)}\frac{92.0}{\left( 93.0 \right)}\frac{94.0}{\left( 93.0 \right)}\frac{94.0}{\left( 95.0 \right)}\frac{96.0}{\left( 95.0 \right)}\frac{96.0}{\left( 97.0 \right)}\frac{98.0}{\left( 97.0 \right)}\frac{98.0}{\left( 99.0 \right)}\frac{100.0}{\left( 99.0 \right)}\frac{100.0}{\left( 101.0 \right)}$
- 3.126078900215408

** Brouncker's Continued Fraction
This is basically equivalent to Wallis' formulation. It's just interestingly recursive, and has a nice pattern.
#+begin_src emacs-lisp :tangle yes  :results value list :exports both
(cl-defun brouncker (n &optional (i 0))
  (if (>= i n) n
    `(/ ,(square (float (+ (* 2 i) 1))) (+ 2 ,(brouncker n (+ 1 i))))))
(let* (
       (br (brouncker 5))
       (wrapped `(/ 4 (+ 1 ,br)))
       (tex (s-wrap (litex-lisp2latex-all wrapped ) "$" "$"))
       (evalled (eval wrapped))
       )
  (list tex evalled))
#+end_src

#+RESULTS:
- $\frac{4}{\left( 1 + \frac{1.0}{\left( 2 + \frac{9.0}{\left( 2 + \frac{25.0}{\left( 2 + \frac{49.0}{\left( 2 + \frac{81.0}{\left( 2 + 5 \right)} \right)} \right)} \right)} \right)} \right)}$
- 3.0896825396825394
** Leibniz Expansion
The derivative of $\arctan{x}$ is $\frac{1}{1+x^2}$, which has power series expansion $\Sum{{-x^{2n}}}{i,0, \infin}$ since it represents the infinite sum of a geometric series. Integrating each term gives us $x- \frac{x^3}{3} + \frac{x^5}{5} \ldots$ as an expansion for $\arctan{x}$. Since $\arctan{1}=\frac{\pi}{4}$, $\pi=4\arctan{1}$, which expands to:
#+begin_src emacs-lisp :tangle yes :results value list :exports both
(let* (
       (leibniz (series `(,(if (math-evenp i) '+ '-) (/ ,(float 4) ,(+ (* 2 i) 1))) i 0 n))
       (wrapped (funcall leibniz 0 LIM))
       (tex (s-wrap (litex-lisp2latex-all wrapped ) "$" "$"))
       (evalled (eval wrapped))
       )
  (list tex evalled))
#+end_src

#+RESULTS:
- $\frac{4.0}{\left( 1 \right)} + -\frac{4.0}{\left( 3 \right)} + \frac{4.0}{\left( 5 \right)} + -\frac{4.0}{\left( 7 \right)} + \frac{4.0}{\left( 9 \right)} + -\frac{4.0}{\left( 11 \right)} + \frac{4.0}{\left( 13 \right)} + -\frac{4.0}{\left( 15 \right)} + \frac{4.0}{\left( 17 \right)} + -\frac{4.0}{\left( 19 \right)} + \frac{4.0}{\left( 21 \right)} + -\frac{4.0}{\left( 23 \right)} + \frac{4.0}{\left( 25 \right)} + -\frac{4.0}{\left( 27 \right)} + \frac{4.0}{\left( 29 \right)} + -\frac{4.0}{\left( 31 \right)} + \frac{4.0}{\left( 33 \right)} + -\frac{4.0}{\left( 35 \right)} + \frac{4.0}{\left( 37 \right)} + -\frac{4.0}{\left( 39 \right)} + \frac{4.0}{\left( 41 \right)} + -\frac{4.0}{\left( 43 \right)} + \frac{4.0}{\left( 45 \right)} + -\frac{4.0}{\left( 47 \right)} + \frac{4.0}{\left( 49 \right)} + -\frac{4.0}{\left( 51 \right)} + \frac{4.0}{\left( 53 \right)} + -\frac{4.0}{\left( 55 \right)} + \frac{4.0}{\left( 57 \right)} + -\frac{4.0}{\left( 59 \right)} + \frac{4.0}{\left( 61 \right)} + -\frac{4.0}{\left( 63 \right)} + \frac{4.0}{\left( 65 \right)} + -\frac{4.0}{\left( 67 \right)} + \frac{4.0}{\left( 69 \right)} + -\frac{4.0}{\left( 71 \right)} + \frac{4.0}{\left( 73 \right)} + -\frac{4.0}{\left( 75 \right)} + \frac{4.0}{\left( 77 \right)} + -\frac{4.0}{\left( 79 \right)} + \frac{4.0}{\left( 81 \right)} + -\frac{4.0}{\left( 83 \right)} + \frac{4.0}{\left( 85 \right)} + -\frac{4.0}{\left( 87 \right)} + \frac{4.0}{\left( 89 \right)} + -\frac{4.0}{\left( 91 \right)} + \frac{4.0}{\left( 93 \right)} + -\frac{4.0}{\left( 95 \right)} + \frac{4.0}{\left( 97 \right)} + -\frac{4.0}{\left( 99 \right)} + \frac{4.0}{\left( 101 \right)}$
- 3.1611986129870506

* Sources
- https://github.com/Atreyagaurav/litex-mode for converting Lisp expressions to valid LaTeX.
- http://www.geom.uiuc.edu/~huberty/math5337/groupe/expresspi.html for the initial ideas.
- https://math.stackexchange.com/questions/8337/different-methods-to-compute-sum-limits-k-1-infty-frac1k2-basel-pro for the proof of the Riemann sum expression.
- https://mindyourdecisions.com/blog/2016/10/12/the-wallis-product-formula-for-pi-and-its-proof/ for proof and history of the Wallis integral expansion.
- https://proofwiki.org/wiki/Power_Series_Expansion_for_Real_Arctangent_Function for part of the proof behind Leibniz' formula.
